name: Deploy Service Product

on:
    push:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'

            - name: Build Project
              run: mvn clean install

            - name: SonarCloud Scan
              run: mvn sonar:sonar -Dsonar.organization=kenzleyfiap -Dsonar.projectKey=${{secrets.PRODUCT_SERVICE_KEY}} -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}

            - name: Login Docker Hub
              run: docker login -u ${{secrets.DOCKER_LOGIN}} -p ${{secrets.DOCKER_PASSWORD}}

            - name: Build docker image
              run: docker build -t luankenzley/product-service .
            - name: Push image docker
              run: docker push luankenzley/product-service